# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rig < Formula
  desc ""
  homepage ""
  version "0.7.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rigdev/rig/releases/download/v0.7.1/rig_darwin_x86_64.tar.gz"
      sha256 "88f2fa1299c23ac65f6ae0a0123f8bbfd4368d4928a97551b146b043e5d00609"

      def install
        bin.install "rig"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rigdev/rig/releases/download/v0.7.1/rig_darwin_arm64.tar.gz"
      sha256 "b49d2b88b68d9dbe9a1bcfcddd8843903015c4dd4eedf22cbeb086364a297db4"

      def install
        bin.install "rig"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rigdev/rig/releases/download/v0.7.1/rig_linux_arm64.tar.gz"
      sha256 "db36811afd78eaecc1f0332470b5ca7587039c3f7d9714f3792b571cedf698b4"

      def install
        bin.install "rig"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/rigdev/rig/releases/download/v0.7.1/rig_linux_x86_64.tar.gz"
      sha256 "9e9ae5cbb035c17af74cb8f872f3cff6e2e206cad11a5ce57dc8edee66e63228"

      def install
        bin.install "rig"
      end
    end
  end
end
