# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class RigOps < Formula
  desc ""
  homepage ""
  version "1.7.6"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/rigdev/rig/releases/download/v1.7.6/rig-ops_darwin_arm64.tar.gz"
      sha256 "aed06170eae842ccffdaeb8d073de713751fb6928d04efafdce29dbac1f9c930"

      def install
        bin.install "rig-ops"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/rigdev/rig/releases/download/v1.7.6/rig-ops_darwin_x86_64.tar.gz"
      sha256 "e0969d63768dd66ea4e06147df7fa96a3e8c2c4ec334cdf2cca6f93dcb35092a"

      def install
        bin.install "rig-ops"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rigdev/rig/releases/download/v1.7.6/rig-ops_linux_arm64.tar.gz"
      sha256 "5786d5bacb43bc235cad4705e79b7e7910c6b5af6d6b1f01962622b53a35c7c5"

      def install
        bin.install "rig-ops"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/rigdev/rig/releases/download/v1.7.6/rig-ops_linux_x86_64.tar.gz"
      sha256 "044c8795fec94b03aa248f3d9a495006bc55a7567c5b7a044076520ec0e0a3c2"

      def install
        bin.install "rig-ops"
      end
    end
  end
end
