# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class RigAdmin < Formula
  desc ""
  homepage ""
  version "0.1.5"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rigdev/rig/releases/download/v0.1.5/rig-server_darwin_x86_64.tar.gz"
      sha256 "3304def052fc7f56bbf8af037ee67c107164f756cf96d4172ef2e268f75b627f"

      def install
        bin.install "rig-admin"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rigdev/rig/releases/download/v0.1.5/rig-server_darwin_arm64.tar.gz"
      sha256 "fbfd4e25d88b7acc1204cbd96bfc46d7581f930a1770cbfe7d9d38084337b038"

      def install
        bin.install "rig-admin"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rigdev/rig/releases/download/v0.1.5/rig-server_linux_arm64.tar.gz"
      sha256 "f72771cde81a5b2990d3057cff3ed5c2f1bc4c7d87d3890f0bfdf5a81ee85181"

      def install
        bin.install "rig-admin"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/rigdev/rig/releases/download/v0.1.5/rig-server_linux_x86_64.tar.gz"
      sha256 "56eb905d95adf185f67cadcf448e78577ed0ddeda6c585086759d0cebb1716dc"

      def install
        bin.install "rig-admin"
      end
    end
  end
end
