# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class RigAdmin < Formula
  desc ""
  homepage ""
  version "1.0.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rigdev/rig/releases/download/v1.0.0/rig-server_darwin_x86_64.tar.gz"
      sha256 "129d43d2ab4446f07f786be8c1c9547c3fcdcfa641aa3330a1034d42a232b106"

      def install
        bin.install "rig-admin"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rigdev/rig/releases/download/v1.0.0/rig-server_darwin_arm64.tar.gz"
      sha256 "64fe22ad0a97367bd3fd31edbae67a43e01d9d1cba8e68b7a0f010500ea138c2"

      def install
        bin.install "rig-admin"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rigdev/rig/releases/download/v1.0.0/rig-server_linux_arm64.tar.gz"
      sha256 "382ccbf767dd325ca0e624b80416f5e03fc5bab23509d1abd8e7118118d86ee6"

      def install
        bin.install "rig-admin"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/rigdev/rig/releases/download/v1.0.0/rig-server_linux_x86_64.tar.gz"
      sha256 "a23de54b9420d0ad2a5470e9d0ada890a182cbf49bcba714b2568e3306d47ad9"

      def install
        bin.install "rig-admin"
      end
    end
  end
end
