# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rig < Formula
  desc ""
  homepage ""
  version "1.7.4"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/rigdev/rig/releases/download/v1.7.4/rig_darwin_arm64.tar.gz"
      sha256 "ee32f50b7478e0342d1bbde228a425d1ce76459e3f28fb15b848a1293a458703"

      def install
        bin.install "rig"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/rigdev/rig/releases/download/v1.7.4/rig_darwin_x86_64.tar.gz"
      sha256 "cb876b86e64a2e1370a6dea2c4e991e878f0efe19af6603bc26e2ec120776117"

      def install
        bin.install "rig"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rigdev/rig/releases/download/v1.7.4/rig_linux_arm64.tar.gz"
      sha256 "3ed328ed15acea01c333abe5c19ca8f4117a65f7b94a3b569ee57684ae036ca8"

      def install
        bin.install "rig"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/rigdev/rig/releases/download/v1.7.4/rig_linux_x86_64.tar.gz"
      sha256 "40cdb9bf09a0eecab5b0af253db5adf5255af2f60450e6009c3fd73920b0e1b0"

      def install
        bin.install "rig"
      end
    end
  end
end
