# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rig < Formula
  desc ""
  homepage ""
  version "1.11.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/rigdev/rig/releases/download/v1.11.1/rig_darwin_arm64.tar.gz"
      sha256 "a1f783fb86bb86f5bacf5b6e8308ca2f7970e1adafd2fe48fcd4545e3122b90f"

      def install
        bin.install "rig"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/rigdev/rig/releases/download/v1.11.1/rig_darwin_x86_64.tar.gz"
      sha256 "5e9e02e305a92e4be2021ac813e4f0cda4fc38f5d2c82a209fa46294896d5f1a"

      def install
        bin.install "rig"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/rigdev/rig/releases/download/v1.11.1/rig_linux_x86_64.tar.gz"
      sha256 "749f4aeabbd2134abc75970c4295892aa83fe2f5d40e56b3c7a48296a886f5ef"

      def install
        bin.install "rig"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rigdev/rig/releases/download/v1.11.1/rig_linux_arm64.tar.gz"
      sha256 "fab09e4a74815303feec4af00e56ebc26efae13e95b5e6ed65dba0a1ab677f3d"

      def install
        bin.install "rig"
      end
    end
  end
end
