# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rig < Formula
  desc ""
  homepage ""
  version "1.6.3"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/rigdev/rig/releases/download/v1.6.3/rig_darwin_arm64.tar.gz"
      sha256 "257292618f8fa44387396803f1718e1d9013693946a412ad36be22cf06451df7"

      def install
        bin.install "rig"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/rigdev/rig/releases/download/v1.6.3/rig_darwin_x86_64.tar.gz"
      sha256 "659e32bb4683d364c37363a569f9742a399e270b4784291833be00e3fa416312"

      def install
        bin.install "rig"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rigdev/rig/releases/download/v1.6.3/rig_linux_arm64.tar.gz"
      sha256 "12fd959b26bab8d77508290018244b26b4fc33c640c15981edf4f514ddde2435"

      def install
        bin.install "rig"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/rigdev/rig/releases/download/v1.6.3/rig_linux_x86_64.tar.gz"
      sha256 "7859fba959a5c326e974342aa43ac030705815352a0311e8b8f955cef8202528"

      def install
        bin.install "rig"
      end
    end
  end
end
